### ISSUE TITLE
Sweep SLP Tokens from paper wallets

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#116]
It would be wonderful for conferences, like the Satoshi Awards, if (paper wallet) tickets could be handed out with a small amount of BCH and tokens on them. Then Badger Mobile could be used to 'sweep' these private keys to retrieve the BCH and tokens.

A perfect example of this is the paper wallets generated at https://paperwallet.bitcoin.com.

This feature would unlock a whole range of use cases like voting, events, golden tickets, tips, etc.

**Comment by SpicyPete** [comment]
Sweeping for BCH is enabled, still need to add SLP sweeping functionality

**Comment by SpicyPete** [comment]
Updating to more fleshed out issue #190
