### ISSUE TITLE
Improve No-BCH error

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#123]
Users are complaining about a common use-case. When a new, inexperienced users receives tokens, they can't send them without some BCH in the wallet. The error they receive is technical and does not indicate a clear solution to guide them to a resolution. The scope of this issue is to improve the error message displayed to the user in this situation.

**Comment by SpicyPete** [comment]
Current error looks something like
`insufficient priority` . 
Better message could look something like 
`Not enough BCH to pay for miner fee.  Add a tiny bit of BCH to the wallet and try again`.  

Open to suggestions.

**Comment by SpicyPete** [comment]
Merged in recent PR.  Included in next update
