### ISSUE TITLE
BIP70 URI scanning

### ISSUE THREAD

**Issue by SpicyPete** [Bitcoin-com/badger-mobile#145]
# BIP70 URI support

Currently Badger Mobile does not support BIP URI's.
When they are scanned, the app resets itself.

- Add support for...
  - [x] Clicking on BIP70 URI's
  - [x] Scanning BIP70 URI's
  - [x] Pasting BIP70 URI's

## Example URI

bitcoincash:?r={payment URL here}

**Comment by cgcardona** [comment]
Need to extend this ticket for pay.bitcoin.com integration.

**Comment by SpicyPete** [comment]
Live in internal builds for testing
