### ISSUE TITLE
CHRIS token crashes the app

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#16]
I sent three tokens to Badger Mobile from Badger Extension:
- CHRIS: 6e1939f066f4da57375299b5cd3b47618e8a925ced5a585595be3cc5d7949360
- HONK: 7f8889682d57369ed0e32336f8b7e0ffec625a35cca183f4e81fde4e71a538a1
- SPICE: 4de69e374a8ed21cbddd47f2338cc0f479dc58daa2bbe11cd604ca488eca0ddf

Clicking on the CHRIS token causes the app to crash. This behavior does not happen when using the HONK or SPICE tokens. 

For testing, contact me and I'll send you some CHRIS tokens.

**Comment by pzenger** [comment]
Confirmed reproducible, investigating

**Comment by pzenger** [comment]
Fixed in above PR
