### ISSUE TITLE
Update ',' to '.' in iOS keyboard

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger-mobile#166]
Bug report via email:

> I tried to use badger wallet app on my iPhone 7 with latest iOS 13 and I can’t send decimals units because the badger wallet app uses , instead of . like the iPhone keyboard uses.
> I tried also on an Samsung S9 so on Android it works just fine because they use . and the keyboard as well so on Android you can send decimal units of a SLP token.
> Thank you for you support in advance.

![tx](https://user-images.githubusercontent.com/260614/65537167-931d5580-deb9-11e9-94c9-b662c3eb3a08.png)

**Comment by SpicyPete** [comment]
Odd, cannot recreate this on any of my own iOS devices.

Anyone else seeing this issue?  Perhaps it's in a language with different localization?  Will continue to investigate
