### ISSUE TITLE
Hide unwanted tokens

### ISSUE THREAD

**Issue by SpicyPete** [Bitcoin-com/badger-mobile#173]
## Problem

* Users can acquire many more tokens than they use, cluttering the UI as they need to sift through 20+ tokens to find the 2 they want/use.

### Solution

* Build a system to optionally hide tokens
* Hidden tokens should appear below the rest, in an expandable `more tokens` section
* Toggle to hide/show token can appear on the token detail screen

**Comment by paOol** [comment]
https://github.com/Bitcoin-com/badger-mobile/pull/225
