### ISSUE TITLE
Feature Request: Rotate app

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#187]
The current implementation of Badger Mobile will not rotate on an Android or iOS. I talked with an active user of Badger Mobile who said it 'doesn't work' on an iPad. After getting it clarified, he meant that it doesn't rotate, and so was 'unusable' by him.

I thought this was a bit odd, but he was very sincere. I'm sure there are other people who would like to use this app on tablet and really want it to rotate.

**Comment by SpicyPete** [comment]
Not going to implement at least for the foreseeable future.  Rotation has been turned off on purpose as there are not enough resource to support rotation across all devices and keep the quality.

**Comment by christroutner** [comment]
Sounds reasonable.
