### ISSUE TITLE
SLP Paper Wallet Sweeping

### ISSUE THREAD

**Issue by SpicyPete** [Bitcoin-com/badger-mobile#190]
from #116 

### Acceptance

- [x] Sweep SLP from paper wallet with no BCH
- [x] Sweep SLP from a paper wallet with both SLP and BCH to respective addresses
- [x] Sweep SLP from a paper wallet with multiple SLP tokens - Multiple sweeps, indicate to user more sweeps will be required
- [x] Sweep BCH only

**Comment by MC76** [comment]
yes, sweep paper wallet SLP tokens is an urgent function, to spread the adoption of slp tokens

**Comment by SpicyPete** [comment]
Almost done, waiting on how to deal with SLP tokens which SLPDB does not know about yet.

**Comment by MC76** [comment]
Why is it necessary that SLPDB knows them?

**Comment by MC76** [comment]
I think the service would be good even for tokens in SLPDB.

**Comment by SpicyPete** [comment]
SLPDB is used by many services to track the validity of tokens, this feature is done now 🙌
