### ISSUE TITLE
BIP21 support basic - Purse.io QR Codes not interpreted

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#26]
Was testing Badger Mobile by making a purchase on Purse.io. I think their QR codes use BIP70? Not sure. Anyways, I tried and failed to take a screenshot of what it looked like after I scanned the QR node. But the address text box came through as something like:

`bitcoincash:qphz6qe0df2c4pj9e5eppnnkwk9fg02kp5s34vu62l?amount=0.08532350`

**Comment by pzenger** [comment]
Good catch, it does not support BIP70 yet.   Should definitely be an added feature before release.
