### ISSUE TITLE
Release to App stores check list

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger-mobile#34]
## Android

* Sign up for a Google Play developer account
* [More steps](https://support.google.com/googleplay/android-developer/answer/113469?hl=en)

## iOS

* [Steps](https://medium.com/@the_manifest/how-to-publish-your-app-on-apples-app-store-in-2018-f76f22a5c33a)

**Comment by SpicyPete** [comment]
Closing and replacing with new issue which can be easier updated
