### ISSUE TITLE
RC2 Feedback

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger-mobile#64]
These are some of the issues I came across while testing Badger Mobile on two cheap (~ $100) Android phones. The 'AT&T' phone mentioned below is an LG K30 running Android 8.1.0.

## Major Issues
- Couldn't add decimal points to the quantity-to-send text box on my AT&T phone, for BCH and tokens.
- Emoji's in the loading screens did not render properly on my AT&T phone, or my Blu R2 phone running Android v7.0.
- Must send in BCH. USD fiat conversion not in place.

## Minor Issues
- No notification when phone receives BCH or token, like the Bitcoin.com wallet does.
- Clicking on a transaction history item does nothing. Would be nice if I could retrieve the TXID or BCH address in a transaction.
- Lack of `send all` button makes it hard to empty out a wallet.

**Comment by SpicyPete** [comment]
Thanks for the feedback report Chris.  I will investigate which of these can be resolved before launch.

**Comment by SpicyPete** [comment]
Created issues to track the work on each of the individual issues.  
Closing this feedback issue, thank you very much @christroutner
