### ISSUE TITLE
Token balance not including all transactions

### ISSUE THREAD

**Issue by truecashtoken** [Bitcoin-com/badger-mobile#80]
Bagder version: 0.4.0 on Android

This bug report regards Tx 0574585faae41d3d50a35a3d1d03119d5e4b5886a61f87d00f60a9c55de869da

- Is visible in the Transaction History of TrueCASH ($TCASH) on badger mobile
- Token amount received is **not updated** in the Balance
- Transaction has >226 confirmations

The same problem occurs in the Crescent mobile SLP wallet. I don't know what's going on, this transaction was sent using Electron Cash SLP 3.4.12 on Linux.

Background information:

Using three different wallets (Electron SLP, Crescent and now Badger mobile) with the same mnemonic. The proper amounts are visible only on Electron SLP edition with seed type bip39? I am not into the technical details just trying to use the same tokens on three devices.

**Comment by SpicyPete** [comment]
Thanks for the report, will look into what is happening here

**Comment by SpicyPete** [comment]
With the recent backend improvements this should be resolved.  
Will reopen if this continues to be an issue.
